### ISSUE TITLE
Crear personaje principal

### ISSUE THREAD

**Issue by sebaspv** [sebaspv/UntitledFruitGame#1]
Crear assets de personaje principal para el videojuego (Manz) de 32*32

**Comment by ManzaneoRULZ** [comment]
![manz](https://user-images.githubusercontent.com/86071976/122462027-b20b2780-cf79-11eb-9606-00f8c30cbc25.png)

Personaje principal (Vista Derecha)

**Comment by ManzaneoRULZ** [comment]
![manz](https://user-images.githubusercontent.com/86071976/122462143-d961f480-cf79-11eb-831c-0c5d177e0561.png)

Personaje principal (Vista central) (Hoja v1)

**Comment by sebaspv** [comment]
@ManzaneoRULZ realiza el commit al folder porfa
